{
 "title": "Windows-MSSQL-Web",
 "description": "Default Icinga for Windows Hyper-V dashboard, providing generic information for Hyper-V plugins for Icinga Web",
 "tags": [
  "mssql",
  "windows",
  "flux"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdbdatasource", "label": "InfluxDB DataSource", "query": "influxdb" },
   { "name": "influxbucket", "label": "Icinga Data", "query": "icinga2" },
   { "name": "hostname", "label": "Hostname", "query": "null" },
   { "name": "service", "label": "Service", "query": "null" }
  ]
 },
 "panels": [
  {
   "title": "${hostname} Backup Problems",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value\" and\r\n    r.hostname == \"${hostname}\" and\r\n    r.metric =~ /::ifw_mssqlbackupstatus::state\\b/ and\r\n    r.service == \"${service}\" and\r\n    r._value != 0\r\n  )\r\n  |> unique(column: \"_field\")\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Unhealthy DB Backups\" }))\r\n  |> count()"
    }
   ]
  },
  {
   "title": "${hostname} DB Health",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value\" and\r\n    r.hostname == \"${hostname}\" and\r\n    r.metric =~ /::ifw_mssqlhealth::state\\b/ and\r\n    r.service == \"${service}\"\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.metric }))"
    }
   ]
  },
  {
   "title": "${hostname} DB Performance Counter",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"value\" and\r\n    r.hostname == \"${hostname}\" and\r\n    r.metric =~ /::ifw_mssqlperfcounter::/ and\r\n    r.service == \"${service}\"\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.metric }))"
    }
   ]
  },
  {
   "title": "${hostname} Stats",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.hostname == \"${hostname}\" and\r\n    (r._field == \"value\" or r._field == \"max\" or r._field == \"min\" or r._field == \"warn\" or r._field == \"crit\") and\r\n    r.service == \"${service}\" and\r\n    r.metric == \"sqlserverbuffermanager::ifw_mssqlresource::buffercachehitratio\"\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.metric }))"
    },
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.hostname == \"${hostname}\" and\r\n    (r._field == \"value\" or r._field == \"max\" or r._field == \"min\" or r._field == \"warn\" or r._field == \"crit\") and\r\n    r.service == \"${service}\" and\r\n    r.metric == \"sqlserverlatches::ifw_mssqlresource::averagelatchwaittimems\"\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.metric }))"
    },
    {
     "query": "from(bucket: \"${influxbucket}\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.hostname == \"${hostname}\" and\r\n    (r._field == \"value\" or r._field == \"max\" or r._field == \"min\" or r._field == \"warn\" or r._field == \"crit\") and\r\n    r.service == \"${service}\" and\r\n    r.metric == \"sqlserverbuffermanager::ifw_mssqlresource::pagelifeexpectancy\"\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: r.metric }))"
    }
   ]
  }
 ]
}